name: CI

# Trigger the CI on pull requests and direct pushes to any branch
on:
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: go get ./...
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Remove pre-installed kustomize
        run: sudo rm -f /usr/local/bin/kustomize
      - name: Run make envtest
        run: make envtest
      - name: Install envtest binaries
        run: ./bin/setup-envtest use 1.19.2
      - name: Perform the test
        run: make test
